export const emptyData = {
  fullname: "Full Name",
  email: "email@example.com",
  phone: "223-0891-910",
  linkedin: "username@linkedin.com",
  schoolName1: "School Name",
  courseName1: "Course Name",
  grade1: "Grade",
  schoolStartDate1: "SchoolStart: MM/YY",
  schoolEndDate1: "SchoolEnd: MM/YY",
  positionName1: "Position Name",
  companyName1: "Company Name",
  location1: "Location",
  jobStartDate1: "JobStart: MM/YY",
  jobEndDate1: "JobEnd: MM/YY",
  jobBullet1: "Job Descrption Bullet 1",
  jobBullet2: "Job Description Bullet 2",
  projectName1: "Project Name",
  projectTools1: "Project Tools",
  projectDate1: "MM/YY",
  projectBullet1: "Project Description Bullet 1",
  projectBullet2: "Project Description Bullet 2",
  languages: "Language like C++",
  frameworks: "Frameworks likew React",
  devTools: "Tools like vs code",
  libraries: "Libraries like numpy",
};
